#include 'protheus.ch' 
#include 'totvs.ch' 
#include 'topconn.ch' 
#include 'tbiconn.ch' 


//--------------------------------------------------------------
/*/{Protheus.doc} WMTRAY06
Description //Cadastra nota fiscal nos pedidos do E-commerce (TRAY)
@param: Nil
@return NIl
@author  - Rafael S.Silva
@since: 16-10-2019 /*/
//--------------------------------------------------------------
User Function WMTRAY06()
    


Return()